# main - Dockerfile for FilipRuman
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine AS runtime
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV NODE_ENV production

CMD ["node", "index.js"]

# Setup Update 1760486901

# Setup Update 1760486901

# Setup Update 1760486901

# Setup Update 1760486901

# Setup Update 1760486901

# Setup Update 1760486901

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902

# Setup Update 1760486902
